- name: prepare image task
  include_tasks: tasks/prepare/{{ prepare_image_task }}.yml
  when: prepare_image_task is defined and prepare_image_task

- name: load image state
  include_tasks: tasks/state/load.yml

- name: set version related facts
  include_tasks: tasks/builder/version.yml

- name: set common labels
  include_tasks: tasks/builder/label.yml

- name: use build cache
  include_tasks: tasks/builder/cache.yml
  when: build_cache | default(false) | bool

- name: force build if image from is built and changed
  when:
    - container_builder_image_from is defined and container_builder_image_from
    - hostvars[container_builder_image_from].dockerfile_builder_image_build is defined
    - hostvars[container_builder_image_from].dockerfile_builder_image_build is changed
  set_fact:
    dockerfile_builder_force_source: true
    dockerfile_builder_force: true

- name: build image
  include_role:
    name: dockerfile_builder

- name: no build, end host here
  when: dockerfile_builder_build_omit | default(false)
  include_tasks: pipeline/end_host.yml

- name: state image build fact
  when:
    - not ansible_check_mode
    - dockerfile_builder_image_info is defined and dockerfile_builder_image_info
  set_fact:
    state_yml_build: true
    state_yml_repo_digest: "{{ dockerfile_builder_image_info.name }}@{{ dockerfile_builder_image_info.manifest.digest }}"

- name: save image state
  include_tasks: tasks/state/save.yml
