- name: prepare image task
  include_tasks: tasks/prepare/{{ prepare_image_task }}.yml
  when: prepare_image_task is defined and prepare_image_task

- name: load image state
  include_tasks: tasks/state/load.yml

- name: set version related facts
  include_tasks: tasks/builder/version.yml

- name: set common labels
  include_tasks: tasks/builder/label.yml

- name: use build cache
  include_tasks: tasks/builder/cache.yml
  when: build_cache | default(false) | bool

- name: force build if image from is built and changed
  when:
    - image_from_ctr is defined and image_from_ctr
    - not hostvars[image_from_ctr].dockerfile_builder_build_omit | default(false)
    - hostvars[image_from_ctr].dockerfile_builder_image_build.changed | default(false)
  set_fact:
    dockerfile_builder_force_source: true
    dockerfile_builder_force: true

- name: build image
  include_role:
    name: dockerfile_builder

- name: omit
  when: not dockerfile_builder_build_omit | default(false)
  block:
    - name: state image build fact
      when:
        - not ansible_check_mode
        - dockerfile_builder_image_info is defined and dockerfile_builder_image_info
      set_fact:
        state_yml_build: true
        state_yml_repo_digest: "{{ dockerfile_builder_image_info.name }}@{{ dockerfile_builder_image_info.manifest.digest }}"

    - name: save image state
      include_tasks: tasks/state/save.yml
