- name: load image state
  include_tasks: tasks/state/load.yml

- name: get container images from state dir
  run_once: true
  vars:
    doc_get_ctr_names: "{{ lookup('pipe', 'find \"' + state_dir + '\" -maxdepth 1 -type f  -name \"*.yml\" -print0 | sort -z | xargs -r0 basename -s .yml').split('\n') }}"
  when:
    - doc_ctr_names_from_state_dir | default(false)
    - doc_get_ctr_names is defined and doc_get_ctr_names
  set_fact:
    doc_ctr_names: "{{ doc_get_ctr_names }}"

- name: generate ctr repo folder file
  when:
    - doc_generate_ctr_repo_readme | default(false)
    - ansible_host in groups[ctr_repo_name | replace('-', '_')]
  block:
    - name: generate ctr repo folder readme
      template:
        src: "{{ doc_generate_ctr_repo_readme_src }}"
        dest: "{{ doc_generate_ctr_repo_readme_dest }}"
        mode: '0644'

    - name: create docs ctr repo folder
      file:
        path: "{{ doc_generate_repo_dest | dirname }}"
        state: directory
        mode: '0755'

    - name: generate docs ctr repo folder file
      template:
        src: "{{ doc_generate_ctr_repo_readme_src }}"
        dest: "{{ doc_generate_repo_dest }}"
        mode: '0644'

- name: copy readme to docs
  when: doc_generate_ctr_readme_src is file
  block:
    - name: create docs ctr dir
      file:
        path: "{{ doc_generate_ctr_dest | dirname }}"
        state: directory
        mode: '0755'

    - name: copy readme to docs
      copy:
        src: "{{ doc_generate_ctr_readme_src }}"
        dest: "{{ doc_generate_ctr_dest }}"

- name: generate project readme
  run_once: true
  when: doc_generate_project_readme | default(false)
  template:
    src: "{{ doc_generate_project_readme_src }}"
    dest: "{{ doc_generate_project_dest }}"
    mode: '0644'
