- name: load image state
  include_tasks: tasks/state/load.yml

- name: save moodle updatebot file
  run_once: true
  when: "'moodle' in ansible_play_hosts_all | join or 'postgres' in ansible_play_hosts_all | join"
  template:
    src: "{{ updatebot_ansible_collection_template_src }}"
    dest: "{{ updatebot_ansible_collection_template_dest }}"
    mode: '0644'
