apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/krestomatio/ansible-collection-k8s
    changes:
    - command:
        # update Moodle image and its tag
        name: bash
        args:
        - -c
        - |
          moodle_image='quay.io/krestomatio/moodle:4.1@sha256:0a336e976620a7a478753e052b91805f57d8953ec1c1f6a339dd25902c67da08'
          sed -i \
            "s#^moodle_image:.*#moodle_image: ${moodle_image//@/\\@}#" \
            roles/v1alpha1/m4e/moodle/defaults/main/moodle.yml
    - command:
        # update Postgres image and its tag
        name: bash
        args:
        - -c
        - |
          postgres_image='quay.io/krestomatio/postgres:13@sha256:c346e05773b1352cc702ad1696402d2bf5adbe6a35beaafac3c92e57c70bb207'
          sed -i \
            "s#^postgres_image:.*#postgres_image: ${postgres_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/postgres.yml
    - command:
        # update Nginx image and its tag
        name: bash
        args:
        - -c
        - |
          nginx_image='quay.io/krestomatio/nginx:1.20@sha256:c28cd1c1b075bcac30615401231f26e9bdc5754256b50c76143564199840c6f1'
          sed -i \
            "s#^nginx_image:.*#nginx_image: ${nginx_image//@/\\@}#" \
            roles/v1alpha1/web/nginx/defaults/main/nginx.yml
    - command:
        # update Keydb image and its tag
        name: bash
        args:
        - -c
        - |
          keydb_image='quay.io/krestomatio/keydb:6.3.4@sha256:e83f4ddeac9795de37fd0ab1f32bab662de157293cadad200f30290470025b58'
          sed -i \
            "s#^keydb_image:.*#keydb_image: ${keydb_image//@/\\@}#" \
            roles/v1alpha1/database/keydb/defaults/main/keydb.yml
    - command:
        # update PgBouncer image and its tag
        name: bash
        args:
        - -c
        - |
          pgbouncer_image='quay.io/krestomatio/pgbouncer@sha256:fc401e5f51e88a014d8250cabc82dd4cd40c95d920a26feebc1ded78f6f00ee0'
          sed -i \
            "s#^pgbouncer_image:.*#pgbouncer_image: ${pgbouncer_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/pgbouncer.yml
    - command:
        # update NFS Ganesha image and its tag
        name: bash
        args:
        - -c
        - |
          nfs_ganesha_image='quay.io/krestomatio/nfs-ganesha:5.5.3@sha256:43a8d3065e20fe5ba3a940a133de0bdcbd5a0fa93cbf9190aa2541cc419e40ff'
          sed -i \
            "s#^ganesha_image:.*#ganesha_image: ${nfs_ganesha_image//@/\\@}#" \
            roles/v1alpha1/nfs/ganesha/defaults/main/ganesha.yml
