apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/krestomatio/ansible-collection-k8s
    changes:
    - command:
        # update Moodle image and its tag
        name: bash
        args:
        - -c
        - |
          moodle_web_image='quay.io/krestomatio/moodle_web@sha256:6f44df77f1eb0156982c5e55640f67ba20fa08ee8448588f88dbb04c60e6b409'
          sed -i \
            "s#^moodle_image:.*#moodle_image: ${moodle_web_image//@/\\@}#" \
            roles/v1alpha1/m4e/m4e/defaults/main/moodle.yml
    - command:
        # update Postgres image and its tag
        name: bash
        args:
        - -c
        - |
          postgres_image='quay.io/krestomatio/postgres@sha256:6806d4db4b57622a5e6616d27228235309ba00a11db7b435533fd77f729160d2'
          sed -i \
            "s#^postgres_image:.*#postgres_image: ${postgres_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/postgres.yml
    - command:
        # update Nginx image and its tag
        name: bash
        args:
        - -c
        - |
          nginx_image='quay.io/krestomatio/nginx@sha256:093161ecef9876c097c16abfef0120b871343326da2599330585907e7007a545'
          sed -i \
            "s#^nginx_image:.*#nginx_image: ${nginx_image//@/\\@}#" \
            roles/v1alpha1/web/nginx/defaults/main/nginx.yml
