apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/krestomatio/ansible-collection-k8s
    changes:
    - command:
        # update Moodle image and its tag
        name: bash
        args:
        - -c
        - |
          moodle_image='quay.io/krestomatio/moodle:4.0@sha256:9855af7d686581b0afb965d506c4228b1dc1ad2c58f7c7175f01285c8cf85564'
          sed -i \
            "s#^moodle_image:.*#moodle_image: ${moodle_image//@/\\@}#" \
            roles/v1alpha1/m4e/moodle/defaults/main/moodle.yml
    - command:
        # update Postgres image and its tag
        name: bash
        args:
        - -c
        - |
          postgres_image='quay.io/krestomatio/postgres:13@sha256:08743a42688d869fd303b4031a62fe01635266fc8699b642ae706dc375ca3ffc'
          sed -i \
            "s#^postgres_image:.*#postgres_image: ${postgres_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/postgres.yml
    - command:
        # update Nginx image and its tag
        name: bash
        args:
        - -c
        - |
          nginx_image='quay.io/krestomatio/nginx:1.20@sha256:ddb6c5f672ba9e1d95e6a14247983671590388063063661818dd4e4201e9b5d8'
          sed -i \
            "s#^nginx_image:.*#nginx_image: ${nginx_image//@/\\@}#" \
            roles/v1alpha1/web/nginx/defaults/main/nginx.yml
    - command:
        # update Keydb image and its tag
        name: bash
        args:
        - -c
        - |
          keydb_image='quay.io/krestomatio/keydb:6.3.1@sha256:ab5e11f09f7e1618f7bee3cc09ed7acc70403260a9bcf7a58fb43f397dffa6cb'
          sed -i \
            "s#^keydb_image:.*#keydb_image: ${keydb_image//@/\\@}#" \
            roles/v1alpha1/database/keydb/defaults/main/keydb.yml
    - command:
        # update PgBouncer image and its tag
        name: bash
        args:
        - -c
        - |
          pgbouncer_image='quay.io/krestomatio/pgbouncer@sha256:7b5f40f76f88ca9d873293d5b34f2d85af545b12bb28df4cae5ac59d6bbcc538'
          sed -i \
            "s#^pgbouncer_image:.*#pgbouncer_image: ${pgbouncer_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/pgbouncer.yml
    - command:
        # update NFS Ganesha image and its tag
        name: bash
        args:
        - -c
        - |
          nfs_ganesha_image='quay.io/krestomatio/nfs-ganesha:4.0.7@sha256:fffd671645cc5daae91b8daf0b5bee3ae0f87840a6e77e69ef3e61b078f0f25b'
          sed -i \
            "s#^ganesha_image:.*#ganesha_image: ${nfs_ganesha_image//@/\\@}#" \
            roles/v1alpha1/nfs/ganesha/defaults/main/ganesha.yml
