apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/krestomatio/ansible-collection-k8s
    changes:
    - command:
        # update Moodle image and its tag
        name: bash
        args:
        - -c
        - |
          moodle_image='quay.io/krestomatio/moodle:4.1@sha256:374275fa92bfa1b05f0313ba3567e4611caf381923da7003347d274817c4966e'
          sed -i \
            "s#^moodle_image:.*#moodle_image: ${moodle_image//@/\\@}#" \
            roles/v1alpha1/m4e/moodle/defaults/main/moodle.yml
    - command:
        # update Postgres image and its tag
        name: bash
        args:
        - -c
        - |
          postgres_image='quay.io/krestomatio/postgres:13@sha256:971b66a834f58b3ab4aa485b535ab0c481e05fca792182437253f4c1a6c1153a'
          sed -i \
            "s#^postgres_image:.*#postgres_image: ${postgres_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/postgres.yml
    - command:
        # update Nginx image and its tag
        name: bash
        args:
        - -c
        - |
          nginx_image='quay.io/krestomatio/nginx:1.20@sha256:1a586775a1af50fece8ead1d1d98da5c4316925e236f852359fc50df9dc32f75'
          sed -i \
            "s#^nginx_image:.*#nginx_image: ${nginx_image//@/\\@}#" \
            roles/v1alpha1/web/nginx/defaults/main/nginx.yml
    - command:
        # update Keydb image and its tag
        name: bash
        args:
        - -c
        - |
          keydb_image='quay.io/krestomatio/keydb:6.3.4@sha256:8bb41f9b4e07b01d3558939bc33f928eed5b4c27e2fa59c108afac2247f0d09e'
          sed -i \
            "s#^keydb_image:.*#keydb_image: ${keydb_image//@/\\@}#" \
            roles/v1alpha1/database/keydb/defaults/main/keydb.yml
    - command:
        # update PgBouncer image and its tag
        name: bash
        args:
        - -c
        - |
          pgbouncer_image='quay.io/krestomatio/pgbouncer@sha256:e7165581a6fe5225a77d4419b12834687789bfe03a0872f08a9d7ab53527f3ac'
          sed -i \
            "s#^pgbouncer_image:.*#pgbouncer_image: ${pgbouncer_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/pgbouncer.yml
    - command:
        # update NFS Ganesha image and its tag
        name: bash
        args:
        - -c
        - |
          nfs_ganesha_image='quay.io/krestomatio/nfs-ganesha:4.0.7@sha256:f766404aabe52e1e0e05c53c4347ec2b7a0989ab065e2785b25fa1f42a6a2522'
          sed -i \
            "s#^ganesha_image:.*#ganesha_image: ${nfs_ganesha_image//@/\\@}#" \
            roles/v1alpha1/nfs/ganesha/defaults/main/ganesha.yml
