apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/krestomatio/ansible-collection-k8s
    changes:
    - command:
        # update Moodle image and its tag
        name: bash
        args:
        - -c
        - |
          moodle_web_image='quay.io/krestomatio/moodle_web@sha256:a59b8922c5b91dc1dd8f668b979dee207e5f6f340c6341e5723ceb42a347ce38'
          sed -i \
            "s#^moodle_image:.*#moodle_image: ${moodle_web_image//@/\\@}#" \
            roles/v1alpha1/m4e/m4e/defaults/main/moodle.yml
    - command:
        # update Postgres image and its tag
        name: bash
        args:
        - -c
        - |
          postgres_image='quay.io/krestomatio/postgres@sha256:dc5ddea01f9ab3138368286194411ef41a6a74413e02be8ad1d9fd4e10db1bab'
          sed -i \
            "s#^postgres_image:.*#postgres_image: ${postgres_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/postgres.yml
    - command:
        # update Nginx image and its tag
        name: bash
        args:
        - -c
        - |
          nginx_image='quay.io/krestomatio/nginx@sha256:aa8ce816691496f187488dcd1a6e4497e349cb841fab8b2387c850a0587cdbef'
          sed -i \
            "s#^nginx_image:.*#nginx_image: ${nginx_image//@/\\@}#" \
            roles/v1alpha1/web/nginx/defaults/main/nginx.yml
    - command:
        # update Keydb image and its tag
        name: bash
        args:
        - -c
        - |
          keydb_image='quay.io/krestomatio/keydb@sha256:a16729f3887a20aa40576719de9c8c954681f98a65761136503a5e0ee334c7bc'
          sed -i \
            "s#^keydb_image:.*#keydb_image: ${keydb_image//@/\\@}#" \
            roles/v1alpha1/database/keydb/defaults/main/keydb.yml
    - command:
        # update PgBouncer image and its tag
        name: bash
        args:
        - -c
        - |
          pgbouncer_image='quay.io/krestomatio/pgbouncer@sha256:71668f4469b8d0925e2f9e85646e1d46ac585ed2765f90609fad426b99fa3235'
          sed -i \
            "s#^pgbouncer_image:.*#pgbouncer_image: ${pgbouncer_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/pgbouncer.yml
    - command:
        # update Graphql Engine image and its tag
        name: bash
        args:
        - -c
        - |
          graphql_engine_image='quay.io/krestomatio/graphql-engine@sha256:15a0c7099134cc6afbbffdf1944e14751e6bb702b45148562a391d054b5969d3'
          sed -i \
            "s#^graphql_engine_image:.*#graphql_engine_image: ${graphql_engine_image//@/\\@}#" \
            roles/v1alpha1/app/g12e/defaults/main/graphql-engine.yml
