apiVersion: updatebot.jenkins-x.io/v1alpha1
kind: UpdateConfig
spec:
  rules:
  - urls:
    - https://github.com/krestomatio/ansible-collection-k8s
    changes:
    - command:
        # update Moodle image and its tag
        name: bash
        args:
        - -c
        - |
          moodle_web_image='quay.io/krestomatio/moodle_web@sha256:7b3f224e1a8c229baa0a42901c1aa79e376ad51216f5e84c0806c5089c12e5f2'
          sed -i \
            "s#^moodle_image:.*#moodle_image: ${moodle_web_image//@/\\@}#" \
            roles/v1alpha1/m4e/m4e/defaults/main/moodle.yml
    - command:
        # update Postgres image and its tag
        name: bash
        args:
        - -c
        - |
          postgres_image='quay.io/krestomatio/postgres@sha256:61099141ea83293fb8aa1c3b32f4d4fd1539061a79ac2487fdb35c79794b8566'
          sed -i \
            "s#^postgres_image:.*#postgres_image: ${postgres_image//@/\\@}#" \
            roles/v1alpha1/database/postgres/defaults/main/postgres.yml
    - command:
        # update Nginx image and its tag
        name: bash
        args:
        - -c
        - |
          nginx_image='quay.io/krestomatio/nginx@sha256:12b16f18818d0bdd35b8bb3f91c601b4ddc59fa59176d9d50d33ace113431a51'
          sed -i \
            "s#^nginx_image:.*#nginx_image: ${nginx_image//@/\\@}#" \
            roles/v1alpha1/web/nginx/defaults/main/nginx.yml
    - command:
        # update Graphql Engine image and its tag
        name: bash
        args:
        - -c
        - |
          graphql_engine_image='quay.io/krestomatio/graphql-engine@sha256:dd287729add38aab36751006d3c9ac8641fdffc1caccdc1f34f77d9da6d641e6'
          sed -i \
            "s#^graphql_engine_image:.*#graphql_engine_image: ${graphql_engine_image//@/\\@}#" \
            roles/v1alpha1/app/g12e/defaults/main/graphql-engine.yml
