- include_tasks: dest.yml

- name: load state related vars
  when:
    - state_vars_load | default(true)
    - state_vars_dest_check.stat.exists
  include_vars:
    dir: "{{ state_dir }}"
    ignore_unknown_extensions: True
    extensions:
      - yml

- name: assign respective state variables
  when: load_state_yml is defined and load_state_yml
  vars:
    load_state_yml: "{{ lookup('vars', state_name + '_image',default=False) }}"
  block:
    - name: set state tag
      when:
        - state_yml_tag is not defined
        - load_state_yml.tag is defined
      set_fact:
        state_yml_tag: "{{ load_state_yml.tag }}"
        load_state_yml_tag: "{{ load_state_yml.tag }}"

    - name: set state repo digest
      when:
        - state_yml_repo_digest is not defined
        - load_state_yml.repo_digest is defined
      set_fact:
        state_yml_repo_digest: "{{ load_state_yml.repo_digest }}"

    - name: set state artifact tag
      when:
        - state_yml_artifact_tag is not defined
        - load_state_yml.artifact_tag is defined
      set_fact:
        state_yml_artifact_tag: "{{ load_state_yml.artifact_tag }}"

    - name: set state relative path
      when:
        - state_yml_relative_path is not defined
        - load_state_yml.relative_path is defined
      set_fact:
        state_yml_relative_path: "{{ load_state_yml.relative_path }}"

    - name: set state suffix tag
      when:
        - state_yml_suffix_tag is not defined
        - load_state_yml.suffix_tag is defined
      set_fact:
        state_yml_suffix_tag: "{{ load_state_yml.suffix_tag }}"

    - name: set state prefix tag
      when:
        - state_yml_prefix_tag is not defined
        - load_state_yml.prefix_tag is defined
      set_fact:
        state_yml_prefix_tag: "{{ load_state_yml.prefix_tag }}"

- name: set fact when artifact matches pipeline's
  when:
    - artifact_tag | default(false)
    - artifact_tag == state_yml_artifact_tag
  set_fact:
    state_image_match_artifact_tag: true
