- name: set config for docker
  run_once: true
  when:
    - dockerfile_builder == 'docker'
    - builder_config | default(false) | bool
  block:
    - when:
      - docker_start_daemon | default(false) | bool
      - not ansible_check_mode
      block:
      - name: check dockerd pid
        command: pidof dockerd
        changed_when: false
        ignore_errors: true
        register: docker_pid_daemon

      - name: start dockerd daemon
        when: docker_pid_daemon.rc != 0
        shell: |
          set -eu
          dockerd-entrypoint.sh &> /tmp/dockerd.log &
          sleep 4

    - name: create config.json
      when:
        - docker_config_json is defined and docker_config_json
      no_log: true
      copy:
        content: |
          {{ docker_config_json }}
        dest: "{{ docker_config_json_path | default('~/.docker/config.json') }}"
        mode: 600

    - name: set default docker context to use
      when: docker_default_context_name | default(false)
      command: "docker context use {{ docker_default_context_name }}"

    - include_tasks: buildx/k8s.yml
      when: dockerfile_builder_use_buildx

    - name: set buildx instance
      when:
        - dockerfile_builder_use_buildx | default(false)
        - dockerfile_builder_use_buildx_instance_name | default(false)
      command: "docker buildx use {{ dockerfile_builder_use_buildx_instance_name }}"
