- name: set destination image name
  when:
    - build_registry_path is defined and build_registry_path
    - registry_path != build_registry_path
  set_fact:
    build_image_name: "{{ build_registry_path }}/{{ ansible_host }}"

- name: tag build image
  command: "{{ dockerfile_builder }} tag {{ container_image }} {{ build_image_name }}"
  changed_when: false

- name: add other tags to image
  when:
    - dockerfile_builder_tags is defined and dockerfile_builder_tags
  register: tag_image_task
  ignore_errors: true
  changed_when: false
  shell: |
    tags=( "{{ dockerfile_builder_tags | join('" "')}}" )
    add_tags () {
      echo "TAGGING: '$1'"
      for tag in "${tags[@]}"
      do
        {{ dockerfile_builder }} tag {{ container_image }} $1:${tag}
        exit_code=$?
        if ! [ $exit_code -eq 0 ]
        then
          echo "TAG: '${tag}'...not added"
        else
          echo "TAG: '${tag}'...added"
        fi
      done
    }
    add_tags {{ build_image_name | default(container_image) }}
    {% if tag_alternative_image_name is defined and tag_alternative_image_name and tag_alternative_image_name != build_image_name | default(container_image) %}
    add_tags {{ tag_alternative_image_name }}
    {% endif %}

- name: show tagging output
  when: tag_image_task.stdout_lines is defined
  debug:
    msg: "{{ tag_image_task.stdout_lines }}"
