- name: add other tags to image
  when:
    - dockerfile_builder_tags is defined and dockerfile_builder_tags
  register: tag_image_task
  ignore_errors: true
  changed_when: false
  shell: |
    set -eu
    tags=( "{{ dockerfile_builder_tags | join('" "')}}" )
    add_tags () {
      echo "TAGGING: '$1'"
      for tag in "${tags[@]}"
      do
        {{ dockerfile_builder }} tag {{ build_container_image }} $1:${tag}
        exit_code=$?
        if ! [ $exit_code -eq 0 ]
        then
          echo "TAG: '${tag}'...not added"
        else
          echo "TAG: '${tag}'...added"
        fi
      done
    }
    add_tags {{ build_container_image }}
    {% if tag_alternative_image_name is defined and tag_alternative_image_name and tag_alternative_image_name != build_container_image %}
    add_tags {{ tag_alternative_image_name }}
    {% endif %}

- name: show tagging output
  when: tag_image_task.stdout_lines is defined
  debug:
    msg: "{{ tag_image_task.stdout_lines }}"
