- name: copy image using skopeo
  include_tasks: skopeo.yml

- name: copy image tags using skopeo
  vars:
    skopeo_dest_image_tag: "{{ item }}"
  loop: "{{ skopeo_dest_image_tags }}"
  include_tasks: skopeo.yml
