- name: copy image
  include_tasks: copy.yml

- name: update repo digest
  when: skopeo_dest_image_digest is defined
  set_fact:
    state_yml_repo_digest: "{{ container_image_variant + '@' + skopeo_dest_image_digest }}"

- name: push container image readme
  include_tasks: pushrm.yml
