- vars:
    skopeo_copy_src_image: "{{ skopeo_copy_src_image_base + ':' + skopeo_src_image_tag if skopeo_src_image_tag is defined and skopeo_src_image_tag else (skopeo_copy_src_image_base_digest if skopeo_copy_src_image_digest != '' else skopeo_src_image) }}"
    skopeo_copy_src_image_base: "{{ skopeo_src_image.split('@')[0].split(':')[0] }}"
    skopeo_copy_src_image_digest: "{{ skopeo_src_image.split('@')[1] | default('') }}"
    skopeo_copy_src_image_base_digest:
      "{{ skopeo_copy_src_image_base + '@' + skopeo_copy_src_image_digest }}"
    skopeo_copy_dest_image: "{{ skopeo_copy_dest_image_base + ':' + skopeo_dest_image_tag if skopeo_dest_image_tag is defined and skopeo_dest_image_tag else (skopeo_copy_dest_image_base_digest if skopeo_copy_dest_image_digest != '' else skopeo_dest_image) }}"
    skopeo_copy_dest_image_base: "{{ skopeo_dest_image.split('@')[0].split(':')[0] }}"
    skopeo_copy_dest_image_digest: "{{ skopeo_dest_image.split('@')[1] | default('') }}"
    skopeo_copy_dest_image_base_digest:
      "{{ skopeo_copy_dest_image_base + '@' + skopeo_copy_dest_image_digest }}"
  when: not ansible_check_mode
  block:
    - name: show source image name
      debug:
        msg: "Source: {{ skopeo_copy_src_image }}"

    - name: show destination image name
      debug:
        msg: "Destination: {{ skopeo_copy_dest_image }}"

    - name: inspect src image
      changed_when: false
      register: skopeo_src_image_inspect
      command: >-
        skopeo inspect {{ '-n' if skopeo_no_tags | default(false) else '' }}
        {{ skopeo_src_transport | default(skopeo_transport) | default('docker://')
        + skopeo_copy_src_image }}

    - name: inspect dest image
      ignore_errors: true
      changed_when: false
      register: skopeo_dest_image_inspect
      command: >-
        skopeo inspect {{ '-n' if skopeo_no_tags | default(false) else '' }}
        {{ skopeo_dest_transport | default(skopeo_transport) | default('docker://')
        + skopeo_copy_dest_image }}

    - name: copy src to dest image
      when:
        - not ansible_check_mode
        - skopeo_dest_image_inspect is failed or
          (skopeo_src_image_inspect.stdout | from_json).Digest !=
          (skopeo_dest_image_inspect.stdout | from_json).Digest
      command: >-
        skopeo copy --all --src-tls-verify={{ skopeo_src_tls_verify | default(true) }}
        --dest-tls-verify={{ skopeo_dest_tls_verify | default(true)}}
        {{ skopeo_src_transport | default(skopeo_transport) | default('docker://')
        + skopeo_copy_src_image }}
        {{ skopeo_dest_transport | default(skopeo_transport) | default('docker://')
        + skopeo_copy_dest_image }}
      throttle: "{{ promote_copy_throttle if promote_copy_throttle is defined and promote_copy_throttle else omit }}"
      retries: 3
      delay: 3
      register: skopeo_copy_status
      until: skopeo_copy_status.rc == 0
